app/controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\FeedbackForm;
use app\models\SignupForm;
use Yii;
use yii\easyii\helpers\Mail;
use yii\easyii\models\Setting;
use yii\easyii\modules\carousel\api\Carousel;
use yii\easyii\modules\catalog\api\Catalog;
use yii\easyii\modules\entity\api\Entity;
use yii\easyii\modules\gallery\api\Gallery;
use yii\easyii\modules\page\api\Page;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class SiteController extends Controller
{
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Главная страница
     * @return string
     */
    public function actionIndex()
    {
        $page = Page::get('index');
        if (!$page) {
            throw new NotFoundHttpException('Item not found.');
        }
        
        return $this->render('index',[
            'page' => $page,
            'gallery' => Gallery::cat('gallery')->getPhotos([
                'pagination'=>[
                    'pageSize'=>1000,
                ],
            ]),
            'spikery' => Catalog::cat('spikery')->getItems(),
            'raspisanie' => Entity::cat('raspisanie')->getItems(),
            'video' => Carousel::items(),
            /*'signupForm' => new SignupForm(),*/
            'feedbackForm' => new FeedbackForm(),
        ]);
    }

    /**
     * Главная страница
     * @return string
     */
    public function actionUchastniki()
    {
        $page = Page::get('ucastniki');
        if (!$page) {
            throw new NotFoundHttpException('Item not found.');
        }

        return $this->render('uchastniki',[
            'page' => $page,
            'ucastniki' => Catalog::cat('ucastniki')->getChildren(),
            'gallery'=>[
                'instagram-blogging' => Gallery::cat('instagram-blogging')->getPhotos([
                    'pagination'=>[
                        'pageSize'=>1000,
                    ],
                ]),
                'youtube-vlogging' => Gallery::cat('youtube-vlogging')->getPhotos([
                    'pagination'=>[
                        'pageSize'=>1000,
                    ],
                ]),
                'multimediynie-longridy' => Gallery::cat('multimediynie-longridy')->getPhotos([
                    'pagination'=>[
                        'pageSize'=>1000,
                    ],
                ]),
                'facebookvkontakte' => Gallery::cat('facebookvkontakte')->getPhotos([
                    'pagination'=>[
                        'pageSize'=>1000,
                    ],
                ]),
            ]
        ]);
    }

    /**
     * Регистрация
     * @return string
     */
    public function actionSignup(){
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'Ваша заявка принята. Администратор в ближайшее время ее подтвердит.');
                Mail::send(
                    Setting::get('admin_email'),
                    'Регистрация участника SBERCAMP',
                    '@app/mail/signup',
                    [
                        'model' => $model,
                        'link' => Url::to(['/admin/feedback'], true)
                    ],
                    [
                        'cc'=>Setting::get('repeat_email'),
                    ]
                );
            }
        }
        return $this->redirect('/');
    }

    /**
     * Отзыв
     * @return string
     */
    public function actionFeedback(){
        $model = new FeedbackForm();
        if ($model->load(Yii::$app->request->post())) {
            $model->save();
            Yii::$app->session->setFlash('success', 'Спасибо, Ваш отзыв принят.');
            /*Mail::send(
                Setting::get('admin_email'),
                'Отзыв участника SBERCAMP',
                '@app/mail/feedback',
                [
                    'model' => $model,
                ],
                [
                    'cc'=>Setting::get('repeat_email'),
                ]
            );*/

        }
        return $this->redirect('/');

    }
}

app/views/site/slides/about.php
<div id="o-proekte" class="row slide choose-us">
    <div class="col-md-12">
        <h2>О проекте</h2>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-lg-10 col-md-9 col-xs-12">
                            <div class="col-md-4 col-xs-12">
                                <p>
                                    <img src="<?= $asset->baseUrl ?>/img/sbercamp.png" class="sbercamp img-responsive"/>
                                </p>
                            </div>
                            <div class="col-md-8 col-xs-12">
                                <p>
                                    SBERCAMP собирает блогеров из разных уголков России. Основные площадки для
                                    публикаций – YouTube и Instagram, LiveJournal, Facebook, Vkontakte.
                                </p>
                            </div>
                            <div class="col-md-12">
                                <p>
                                    SBERCAMP –
                                    концентрация знаний о трендах видеоблогинга, медиа-форматов, эффективном контенте, написании
                                    мультимедийных лонгридов и идеальных постов.
                                    Присоединяйся! Тебя ждет насыщенная программа: мастер-класс по нативной рекламе, обучающие
                                    тренинги в потоках по тематикам с участием приглашенных спикеров, творческие задания и, конечно,
                                    интерактивные мероприятия.
                                </p>
                                <p>
                                    Здесь ты узнаешь как подготовить коммерческий контент так, чтобы учесть интересы всех: когда
                                    подписчики в восторге, а заказчик доволен. Что нужно знать о работе с брендом, чтобы крупнейшие
                                    компании страны стремились с тобой сотрудничать.
                                </p>
                            </div>
                        </div>
                        <div class="col-lg-2 col-md-3 col-sm-4 col-xs-12">
                            <h4>При поддержке</h4>
                            <div class="support-img text-center">
                                <img src="<?= $asset->baseUrl ?>/img/hello_b.png" class="img-responsive"/>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/site/slides/address.php
<?php
/** @var $page \yii\easyii\modules\page\api\PageObject */
use yii\easyii\models\Setting;
use yii\helpers\Url;

?>
<div id="kontakty" class="row delimiter-line slide choose-us">
    <div class="col-md-12">
        <h2>Контакты</h2>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-3">
                            <p class="address-p">Адрес:</p>
                            <p>
                                Ставропольский край,<br>
                                г. Кисловодск,<br>
                                Курортный бульвар, 14
                            </p>
                        </div>
                        <div class="col-md-9">
                            <?php
                            $parts = explode("#", $page->data->address);
                            if (count($parts) == 4): ?>
                                <div id="map"></div>
                                <script>

                                    function initMap() {
                                        var pinColor = "83d924";
                                        var pinImage = new google.maps.MarkerImage("http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=%E2%80%A2|" + pinColor,
                                            new google.maps.Size(31, 44),
                                            new google.maps.Point(0,0),
                                            new google.maps.Point(10, 34),
                                            new google.maps.Size(31, 44));
                                        var pinShadow = new google.maps.MarkerImage("http://chart.apis.google.com/chart?chst=d_map_pin_shadow",
                                            new google.maps.Size(40, 37),
                                            new google.maps.Point(0, 0),
                                            new google.maps.Point(12, 35));


                                        var myLatLng = {lat: <?= $parts[2] ?>, lng: <?= $parts[3] ?>};

                                        var map = new google.maps.Map(document.getElementById('map'), {
                                            zoom: 17,
                                            center: myLatLng
                                        });

                                        var marker = new google.maps.Marker({
                                            position: myLatLng,
                                            map: map,
                                            icon: '<?=Url::to($asset->baseUrl, true)?>/img/marker.png'
                                            /*icon: pinImage,
                                             shadow: pinShadow*/
                                        });
                                    }

                                </script>
                                <script async defer
                                        src="https://maps.googleapis.com/maps/api/js?key=<?= Setting::get('gm_api_key') ?>&signed_in=true&callback=initMap&language=<?= Yii::$app->language ?>"></script>
                                <?php /*
                        <iframe width="100%" height="445" frameborder="0" style="border:0"
                                src="https://www.google.com/maps/embed/v1/place?q=place_id:<?= $parts[1] ?>&key=<?= Setting::get('gm_api_key') ?>&language=<?= Yii::$app->language ?>"
                        ></iframe>
                        */ ?>
                            <?php endif;  ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/site/slides/evolution.php
<?php
/** @var $asset \yii\web\AssetBundle */

use yii\helpers\Url;
?>

<div id="istoriya" class="row delimiter-line slide choose-us">
    <div class="col-md-12">
        <h2>История мероприятия SBERCAMP</h2>
<?php /*        <p class="text-center">Вы можете посмотреть всю историю обновлений сайта SBERCAMP.</p> */ ?>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-12">
                            <section class="timeline gallerycontainer">
                                <ul>
                                    <li>
                                        <div>
                                            <p>Сентябрь 2016</p>
                                            <time>Тюмень</time>
                                            <p><a class="thumb" href="http://2016.sbercamp.ru">ПРОСМОТРЕТЬ<span><img src="<?=Url::to($asset->baseUrl, true)?>/img/thumb-2016.png" /></span></a></p>
                                        </div>
                                    </li>
                                    <li>
                                        <div>
                                            <p>Март 2017</p>
                                            <time>Кисловодск</time>
                                            <p><a class="thumb" href="/">ПРОСМОТРЕТЬ<span><img src="<?=Url::to($asset->baseUrl, true)?>/img/thumb-2017.png" /></span></a></p>
                                        </div>
                                    </li>
                                    <li>
                                        <div>
                                            <p>Июль 2017</p>
                                            <time>Владивосток</time>
                                            <?php /*<p><a class="thumb" href="http://2018.sbercamp.ru">ПРОСМОТРЕТЬ<span><img src="<?=Url::to($asset->baseUrl, true)?>/img/thumb-2017.png" /></span></a></p>*/?>
                                        </div>
                                    </li>
                                </ul>
                            </section>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php
$script = <<<JS
    (function() {
    
      'use strict';
    
      // define variables
      var items = document.querySelectorAll(".timeline li");
    
      // check if an element is in viewport
      // http://stackoverflow.com/questions/123999/how-to-tell-if-a-dom-element-is-visible-in-the-current-viewport
      function isElementInViewport(el) {
        var rect = el.getBoundingClientRect();
        return (
          rect.top >= 0 &&
          rect.left >= 0 &&
          rect.bottom <= (window.innerHeight || document.documentElement.clientHeight) &&
          rect.right <= (window.innerWidth || document.documentElement.clientWidth)
        );
      }
    
      function callbackFunc() {
        for (var i = 0; i < items.length; i++) {
          if (isElementInViewport(items[i])) {
            items[i].classList.add("in-view");
          }
        }
      }
    
      // listen for events
      window.addEventListener("load", callbackFunc);
      window.addEventListener("resize", callbackFunc);
      window.addEventListener("scroll", callbackFunc);
    
    })();
JS;
$this->registerJs($script, yii\web\View::POS_READY);
?>

app/views/site/slides/feedback.php
<?php
/** @var $feedbackForm \app\models\FeedbackForm */
/** @var $asset \yii\web\AssetBundle */

use yii\helpers\Url;
use yii\widgets\ActiveForm;

?>
<div id="ocenit" class="row delimiter-line slide choose-us">
    <div class="col-md-12">
        <h2>Оцените наше мероприятие</h2>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-auth form-rounded">
                        <?php $form = ActiveForm::begin([
                            'id' => 'form-reg',
                            'enableClientValidation' => true,
                            'action' => Url::to(['/site/feedback'])
                        ]); ?>

                        <?= $form->field($feedbackForm, 'blok', [
                            'template' => "{label}\n<ul class=\"feedback-mark\">{input}</ul>\n",
                        ])->radioList($feedbackForm->marks(),[
                            'item' => function($index, $label, $name, $checked, $value) {

                                $return = '<li>';
                                $return .= '<input type="radio" name="' . $name . '" value="' . $value . '" id="' . $name . $index.'" />';
                                $return .= '<label for="' . $name . $index.'">'.$value.'</label>';
                                $return .= '</li>';

                                return $return;
                            }
                        ]) ?>


                        <?= $form->field($feedbackForm, 'spiker', [
                            'template' => "{label}\n<ul class=\"feedback-mark\">{input}</ul>\n",
                        ])->radioList($feedbackForm->marks(),[
                            'item' => function($index, $label, $name, $checked, $value) {

                                $return = '<li>';
                                $return .= '<input type="radio" name="' . $name . '" value="' . $value . '" id="' . $name . $index.'" />';
                                $return .= '<label for="' . $name . $index.'">'.$value.'</label>';
                                $return .= '</li>';

                                return $return;
                            }
                        ]) ?>

                        <?= $form->field($feedbackForm, 'novizna', [
                            'template' => "{label}\n<ul class=\"feedback-mark\">{input}</ul>\n",
                        ])->radioList($feedbackForm->marks(),[
                            'item' => function($index, $label, $name, $checked, $value) {

                                $return = '<li>';
                                $return .= '<input type="radio" name="' . $name . '" value="' . $value . '" id="' . $name . $index.'" />';
                                $return .= '<label for="' . $name . $index.'">'.$value.'</label>';
                                $return .= '</li>';

                                return $return;
                            }
                        ]) ?>

                        <?= $form->field($feedbackForm, 'polza', [
                            'template' => "{label}\n<ul class=\"feedback-mark\">{input}</ul>\n",
                        ])->radioList($feedbackForm->marks(),[
                            'item' => function($index, $label, $name, $checked, $value) {

                                $return = '<li>';
                                $return .= '<input type="radio" name="' . $name . '" value="' . $value . '" id="' . $name . $index.'" />';
                                $return .= '<label for="' . $name . $index.'">'.$value.'</label>';
                                $return .= '</li>';

                                return $return;
                            }
                        ]) ?>

                        <?= $form->field($feedbackForm, 'atmo', [
                            'template' => "{label}\n<ul class=\"feedback-mark\">{input}</ul>\n",
                        ])->radioList($feedbackForm->marks(),[
                            'item' => function($index, $label, $name, $checked, $value) {

                                $return = '<li>';
                                $return .= '<input type="radio" name="' . $name . '" value="' . $value . '" id="' . $name . $index.'" />';
                                $return .= '<label for="' . $name . $index.'">'.$value.'</label>';
                                $return .= '</li>';

                                return $return;
                            }
                        ]) ?>

                        <?= $form->field($feedbackForm, 'org', [
                            'template' => "{label}\n<ul class=\"feedback-mark\">{input}</ul>\n",
                        ])->radioList($feedbackForm->marks(),[
                            'item' => function($index, $label, $name, $checked, $value) {

                                $return = '<li>';
                                $return .= '<input type="radio" name="' . $name . '" value="' . $value . '" id="' . $name . $index.'" />';
                                $return .= '<label for="' . $name . $index.'">'.$value.'</label>';
                                $return .= '</li>';

                                return $return;
                            }
                        ]) ?>

                        <?= $form->field($feedbackForm, 'isp')->textarea(['rows'=>4]) ?>
                        <?= $form->field($feedbackForm, 'pozh')->textarea(['rows'=>4]) ?>

                        <div class="clearfix"></div>
                        <div class="btn-send">
                            <input type="submit" id="btn-send" value="ОТПРАВИТЬ" class="btn btn-success">
                        </div>
                        <?php ActiveForm::end(); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/site/slides/gallery.php
<?php
/** @var $gallery \yii\easyii\modules\gallery\api\PhotoObject[] */

?>

<div id="galereya" class="row delimiter-line slide choose-us">
    <div class="col-md-12">
        <h2>Галерея</h2>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="clearfix mosaicflow" data-min-item-width="300">
                                <?php foreach (array_slice($gallery, 0, 9) as $item): ?>
                                    <div class="mosaicflow__item">
                                        <a href="<?= $item->getImage() ?>" class="photo">
                                            <img src="<?= $item->getImage() ?>" class="img-thumbnail">
                                        </a>
                                    </div>
                                <?php endforeach; ?>
                                <?php
                                //Просмотр всех фоток в слайдшоу
                                ?>
                                <?php foreach (array_slice($gallery, 9) as $item): ?>
                                    <a href="<?= $item->getImage() ?>" class="photo" style="display: none;">
                                        <img src="<?= $item->getImage() ?>" class="img-thumbnail">
                                    </a>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/site/slides/main.php
<div id="slide-main" class="row delimiter-line">
    <div class="col-md-12 nopadding">
        <div class="main-form container">
            <div class="row">
                <div class="col-md-8">
                    <div class="sec1_image1">
                        <img src="<?= $asset->baseUrl ?>/img/sbercamp_1.png" class="img-responsive"/>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 col-md-offset-6">
                    <div class="sec1_image1">
                        <img src="<?= $asset->baseUrl ?>/img/59.png" class="img-responsive"/>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/site/slides/shedule.php
<?php
/**
 * @var $this \yii\web\View
 * @var $asset \yii\web\AssetBundle
 * @var $raspisanie \yii\easyii\modules\entity\api\ItemObject[]
 */
?>
<div id="raspisanie" class="row delimiter-line slide choose-us">
    <div class="col-md-12">
        <h2>Расписание</h2>
        <div class="main-form container">
            <div class="row">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-lg-12 col-lg-offset-0 col-md-8 col-md-offset-2 col-xs-10 col-xs-offset-1">
                            <div class="shedule-menu">
                                <ul id="shedule-tabs" class="nav nav-pills" role="tablist">
                                    <?php foreach ($raspisanie as $key => $rasp) : ?>
                                        <li role="presentation"<?php if ($key == 1) : echo ' class="active"'; endif; ?>>
                                            <a id="sh-<?= $key; ?>" class="btn btn-success" role="tab" data-toggle="tab"
                                               aria-controls="shedule-<?= $key; ?>" href="#shedule-<?= $key; ?>">
                                                <strong><?= $rasp->data->date; ?></strong>
                                                <br> <?= str_replace('|', '<br>', $rasp->getTitle()); ?>
                                            </a>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2">
                            <div class="tab-content">
                                <?php foreach ($raspisanie as $key => $rasp) : ?>
                                    <div id="shedule-<?= $key; ?>" role="tabpanel"
                                         class="shedule-table tab-pane<?php if ($key == 1) : echo ' active'; endif; ?>">
                                        <?= $rasp->data->desc; ?>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/site/slides/signup.php
<?php
/** @var $signupForm \app\models\SignupForm */
/** @var $asset \yii\web\AssetBundle */

use yii\helpers\Url;
use yii\widgets\ActiveForm;

?>
<div id="registracia" class="row delimiter-line slide choose-us">
    <div class="col-md-12">
        <h2>Регистрация</h2>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-4 col-xs-12">
                            <h2 class="sbercamp-head">SBERCAMP</h2>
                            <p class="text-left">
                                Присоединяйся! Окунись в насыщенную программу обучающих тренингов по интересным
                                тематикам,
                                мастер-классов, проводимых приглашенными спикерами, творческих заданий и, конечно,
                                интерактивных
                                мероприятий.
                            </p>
                        </div>
                        <div class="col-md-8 col-xs-12">
                            <div class="form-auth form-rounded">
                                <?php $form = ActiveForm::begin([
                                    'id' => 'form-reg',
                                    'enableClientValidation' => true,
                                    'action' => Url::to(['/site/signup'])
                                ]); ?>
                                <div class="row">
                                    <div class="col-md-6 col-xs-12">
                                        <?= $form->field($signupForm, 'fio', [
                                            'template' => "{input}\n{error}",
                                            'inputOptions' => [
                                                'class' => 'form-control input-lg',
                                            ],
                                        ])
                                            ->textInput([
                                                'placeholder' => $signupForm->getAttributeLabel('fio')
                                            ]); ?>
                                        <?= $form->field($signupForm, 'phone', [
                                            'template' => "{input}\n{error}",
                                            'inputOptions' => [
                                                'class' => 'form-control input-lg',
                                            ],
                                        ])
                                            ->textInput([
                                                'placeholder' => $signupForm->getAttributeLabel('phone')
                                            ]); ?>

                                        <?= $form->field($signupForm, 'email', [
                                            'template' => "{input}\n{error}",
                                            'inputOptions' => [
                                                'class' => 'form-control input-lg',
                                            ],
                                        ])
                                            ->textInput([
                                                'placeholder' => $signupForm->getAttributeLabel('email')
                                            ]); ?>

                                        <?= $form->field($signupForm, 'section', [
                                            'template' => "{input}\n{error}",
                                            'inputOptions' => [
                                                'class' => 'form-control input-lg select-img',
                                            ],
                                        ])
                                        ->dropDownList($signupForm->fieldOptions(), [
                                            'prompt' => $signupForm->getAttributeLabel('section'),
                                            'options' => $signupForm->optionSections,
                                        ]); ?>
                                    </div>

                                    <div class="col-md-6 col-xs-12">
                                        <div class="flask">
                                            <img src="<?= $asset->baseUrl ?>/img/flask.png" class="img-responsive" id="flask"/>
                                            <img src="<?= $asset->baseUrl ?>/img/flask-3.png" class="img-responsive" id="flask-3" style="display: none;" />
                                            <img src="<?= $asset->baseUrl ?>/img/flask-4.png" class="img-responsive" id="flask-4" style="display: none;" />
                                            <img src="<?= $asset->baseUrl ?>/img/flask-5.png" class="img-responsive" id="flask-5" style="display: none;" />
                                            <img src="<?= $asset->baseUrl ?>/img/flask-6.png" class="img-responsive" id="flask-6" style="display: none;" />
                                        </div>
                                        <div class="btn-send">
                                            <input type="submit" id="btn-send" value="ОТПРАВИТЬ" class="btn btn-success">
                                        </div>
                                        <?php ActiveForm::end(); ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php
$script = <<<JS
$(document).ready(function(){
    var flasks = $(".flask");
	$(".select-img").change(function() {
	    var key = $(".select-img option:selected").val();
	    if (key != "") {
	        key = "-" + key;
	    }
	    flasks.find("img").hide();
	    $("#flask" + key, flasks).show();
	});
});
JS;
$this->registerJs($script, yii\web\View::POS_READY);
?>